# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85c5c2a015657c15b2e9a07528e409c12c752ba3f90a967dd6a8f2cebb30300b03adfa5eabed1aed7eee33e6e12ad883affb1411e598fc49f321d9b86ede714b

test:
  secret_key_base: 8764d707eda6719ff5f04437ee80b3ad57b6755b8c4830077c52dfd50a9db338b8f2a7e52170d698d3fea06d076b9c3a2abe5e6f7c41aaddb8d5630a2f6a0dc3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
